In [1]:
import numpy as np
import torch

In [8]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
nums.shape

torch.Size([9])

In [10]:
type(nums)

torch.Tensor

In [11]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [12]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [13]:
randoms = torch.rand((3,3))
randoms

tensor([[0.2851, 0.7853, 0.3007],
        [0.3541, 0.2514, 0.9283],
        [0.2381, 0.5004, 0.3943]])

In [14]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
ones = torch.ones((3, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
zeros.size()

torch.Size([3, 3])

numpy이랑 다를바가 없음

수학연산

In [19]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [20]:
nums = nums.reshape((3,3))

In [22]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [27]:
result = torch.add(nums, 10)
result

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [28]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int64)

### View

In [29]:
range_nums = torch.arange(9).reshape(3, 3)

In [30]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [31]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
range_nums.view(1,9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

slicing과 indexing도 됨

numpy를 torch tensor로 불러오기

In [33]:
arr = np.array([1, 1, 1])
arr

array([1, 1, 1])

In [34]:
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 1, 1], dtype=torch.int32)

In [36]:
arr_torch.float()

tensor([1., 1., 1.])

In [41]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' # cuda가 감지되면 gpu로

In [42]:
device

'cpu'

In [43]:
arr_torch.to(device) # cpu로 컴파일 됨

tensor([1, 1, 1], dtype=torch.int32)

## AutoGrad

In [44]:
x = torch.ones(2, 2, requires_grad=True)

In [45]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [46]:
print(y.grad_fn)

In [47]:
z = y * y * 3
out = z.mean()

In [48]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [49]:
out.backward()

In [50]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [52]:
print(x.requires_grad)
print((x** 2).requires_grad)

True
True


In [53]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [55]:
torch.FloatTensor([1.,2.]).mean()

tensor(1.5000)

In [57]:
t = torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [58]:
t.mean(), t.mean(dim=0), t.mean(dim=1), t.mean(dim=-1)

(tensor(2.5000),
 tensor([2., 3.]),
 tensor([1.5000, 3.5000]),
 tensor([1.5000, 3.5000]))

In [59]:
t.max(),t.max(dim=0),t.max(dim=1),t.max(dim=-1)

(tensor(4.), torch.return_types.max(
 values=tensor([3., 4.]),
 indices=tensor([1, 1])), torch.return_types.max(
 values=tensor([2., 4.]),
 indices=tensor([1, 1])), torch.return_types.max(
 values=tensor([2., 4.]),
 indices=tensor([1, 1])))