In [1]:
import torch
from torch.autograd import Variable

In [2]:
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
x_variable = Variable(x_tensor)
x_variable

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Variable은 Tensor를 감싸는 형태

In [4]:
x_variable.data

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
print(x_variable.grad) #Gradient도 저장됨 but 현재는 학습을 수행하지 않았으므로 None값을 반환함

None


In [7]:
print(x_variable.requires_grad)

x_variable = Variable(x_tensor, requires_grad=True)
x_variable.requires_grad

False


True

requires_grad=True 옵션을 줘야 gradient를 계산함

In [9]:
# volatile - inference 할때 쓰임 (불필요한 연산을 제거하고 feedforward만 수행) 그러나 이제 안 쓰이는듯 Warning 발생
x_variable = Variable(x_tensor, volatile=True)
x_variable.grad, x_variable.requires_grad, x_variable.volatile

C:\Users\SHM\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  
C:\Users\SHM\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: volatile was removed (Variable.volatile is always False)
  This is separate from the ipykernel package so we can avoid doing imports until


(None, False, False)

In [17]:
# create graph(
X = Variable(torch.FloatTensor(3,4), requires_grad=True)
y = X**2 + 4*X
z = 2*y + 3

X.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [18]:
# .backward(gradient, retain_graph, create_graph, retain_variables)
# compute gradient of current variable w, r, t. graph leaves

loss = torch.FloatTensor(3,4)
z.backward(loss)

print(X.grad)
y.grad, z.grad

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


(None, None)